# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tcl-Tk
version:      0.87
version_from: lib/Tcl/Tk.pm
installdirs:  site
requires:
    Tcl:                           0.85

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
