# http://module-build.sourceforge.net/META-spec.html
name:         Tcl-Tk
version_from: lib/Tcl/Tk.pm
installdirs:  site
requires:
  Tcl::Tk: 0.6
index:
  file:
  - lib/Tcl/Tk.pm
no_index:
  dir:
  - demos
  - tk-demos
keywords:
- Tk
- Tcl/Tk/Tix
- GUI
auto_regenerate: false
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21_01
